POST http://localhost:5000/api/url/shorten HTTP/1.1
content-type: application/json

{
    "longUrl" : "https://www.amazon.fr/support-reglable-pour-echo-show-8-2e-generation/dp/B08KFKZ4XS/?pf_rd_r=3SGZKJAGC2QQ85RR5NC1&pf_rd_p=d965b23c-62ed-48b5-869c-b7bb891430a3&pd_rd_r=37ea3172-7320-48b5-852d-68edcc237873&pd_rd_w=JQeCW&pd_rd_wg=01CWy&ref_=pd_gw_unk"
}

###
GET http://localhost:5000/H5bWQCxi9E1PPUFkXWzX6 HTTP/1.1
content-type: application/json